name: jazzy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:noble
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.13
        with:
          required-ros-distributions: jazzy
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.3
        with:
          package-name: robot_msr
          target-ros2-distro: jazzy
          skip-test: true
          colcon-defaults: |
            {
              "build": {
                "packages-up-to": true
              }
            }